version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Python dependencies (requirements.txt, pyproject.toml)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"  # Frontend dependencies (package.json)
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"  # CI/CD workflow updates
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"  # Java build system (if used)
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"  # Dockerfile base image updates
    schedule:
      interval: "weekly"
