version: 2
updates:
  # Python (pip)
  - package-ecosystem: "pip"
    directory: "/"                      # where requirements.txt / pyproject.toml lives
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # JavaScript (npm or yarn)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions (keeps your actions up to date)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Gradle (if you use it)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
