version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/python-app"                  # requirements.txt and pyproject.toml live here
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"           # GitHub Actions workflows
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/python-app"                  # Dockerfile lives here
    schedule:
      interval: "weekly"
