version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"  # requirements.txt and pyproject.toml are in root
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"  # Dockerfile is in root
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
