version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"                            # requirements.txt must be here
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"                            # package.json must be here
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"            # points to actual workflow folder
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"                            # build.gradle must be here
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"                            # Dockerfile must be here
    schedule:
      interval: "weekly"
