# CI pipeline: build, test, scan (Trivy), publish image to JFrog Artifactory using Vault
name: ci-build-and-push

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: python-service
  PYTHON_VERSION: '3.10'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests (fail on real test failures, allow "no tests collected")
        run: |
          pytest || RC=$?
          if [ "${RC:-0}" -eq 5 ]; then
            echo "No tests were collected by pytest (exit code 5). Continuing."
          elif [ "${RC:-0}" -ne 0 ]; then
            echo "pytest failed with exit code ${RC}"; exit ${RC}
          fi

      - name: Authenticate with Vault (GitHub OIDC)
        id: vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          path: jwt
          role: gh-actions
          jwtGithubAudience: https://github.com/${{ github.repository_owner }}
          namespace: ${{ secrets.VAULT_NAMESPACE }}
          exportEnv: true
          secrets: |
            ci/data/artifactory url          | ARTIFACTORY_URL
            ci/data/artifactory repo_docker  | DOCKER_REPO
            ci/data/artifactory username     | ARTIFACTORY_USER
            ci/data/artifactory password     | ARTIFACTORY_PASSWORD

      - name: Build Docker image
        id: build-image
        run: |
          SHORT="$(git rev-parse --short HEAD)"
          IMAGE_TAG="${IMAGE_NAME}:ci-${SHORT}"
          docker build -t "$IMAGE_TAG" .
          echo "local_image=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Scan image with Trivy (pinned action)
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ${{ steps.build-image.outputs.local_image }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Docker login to JFrog Artifactory
        run: |
          echo "$ARTIFACTORY_PASSWORD" | docker login "$ARTIFACTORY_URL" -u "$ARTIFACTORY_USER" --password-stdin

      - name: Tag & push image to Artifactory
        id: push-image
        run: |
          SHORT="$(git rev-parse --short HEAD)"
          IMAGE_ARTIFACT="${ARTIFACTORY_URL}/${DOCKER_REPO}/${IMAGE_NAME}:${SHORT}"
          docker tag "${{ steps.build-image.outputs.local_image }}" "$IMAGE_ARTIFACT"
          docker push "$IMAGE_ARTIFACT"
          echo "image_artifact=$IMAGE_ARTIFACT" >> $GITHUB_OUTPUT
          echo "$IMAGE_ARTIFACT" > image-tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt
