name: Fast CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle.properties"
      - "gradle/wrapper/**"
      - "gradlew"
      - "gradlew.bat"
  pull_request:

permissions:
  contents: read

concurrency:
  group: selfhosted-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 5
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Java (cached)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Run ultra-fast CI task
        run: ./gradlew -q ci
