name: build-and-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  VAULT_ADDR: http://127.0.0.1:8212
  APP_NAME: python-app
  IMAGE_NAME: hello-world
  HEALTH_URL: http://localhost:8080/health

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: ci • build & push
    runs-on: [self-hosted, Linux, X64]
    outputs:
      image_ref: ${{ steps.meta.outputs.image_ref }}
    steps:
      - uses: actions/checkout@v4

      - name: debug • inspect OIDC token
        run: |
          echo "${ACTIONS_ID_TOKEN}" | cut -d '.' -f2 | base64 -d | jq || echo "OIDC token inspection failed"

      - name: vault • read jfrog creds (oidc)
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          method: jwt
          role: gh-actions
          path: jwt
          exportEnv: true
          secrets: |
            ci/data/artifactory url          | ART_URL;
            ci/data/artifactory repo_docker  | ART_DOCKER_REPO;
            ci/data/artifactory username     | ART_USER;
