name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/test-runner.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  VAULT_ADDR: http://127.0.0.1:8212
  VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
  HEALTH_URL: https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/health
  IMAGE_NAME: hello-world

jobs:
  build-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest || echo "No tests found"

      - name: Inspect GitHub OIDC token
        run: |
          TOKEN_URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://github.com/${{ github.repository_owner }}"
          IDTOKEN="$(curl -s -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "$TOKEN
