name: Python-test CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - run: |
          python3 src/main/python/app.py
          echo "✅ CI POC done."
