name: Self-Hosted Runner Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: selfhosted-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]   # match your runner labels
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Java (for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (venv)
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run Python App via Gradle (stable settings)
        env:
          GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx1g"'
        run: ./gradlew --no-daemon --max-workers=1 --stacktrace --info runApp

      - name: Run tests (optional)
        if: always()
        run: |
          . .venv/bin/activate
          python -m pytest -q || true
