# .github/workflows/test-runner.yml
name: Self-Hosted Runner Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java (for Gradle)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run Python App via Gradle (no daemon, fewer workers, more heap)
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xms256m -Xmx1g"
        run: ./gradlew --no-daemon --max-workers=1 --stacktrace --info runApp
