name: CI - Python POC & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run app.py (quick POC)
        run: |
          python3 src/main/python/app.py || true
          echo "✅ app.py executed"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packaging tools
        run: python -m pip install -q --upgrade pip build twine

      - name: Build Python package
        run: python -m build

      - name: Publish to JFrog
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
          twine upload \
            --repository-url "${JFROG_URL}/api/pypi/pypi/" \
            -u "${JFROG_USER}" -p "${JFROG_TOKEN}" \
            dist/*
