name: Python-test CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "src/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: selfhosted-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 1
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run ultra-fast POC step
        run: |
          python3 src/main/python/app.py
          echo "✅ CI POC done."
